name: sandeny
version: 1.0.0+6
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  agora_uikit: ^1.3.7
  amazon_payfort: ^1.1.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.6
  custom_navigation_bar: ^0.8.2
  dash_chat_2: ^0.0.19
  device_info_plus: null
  dio: ^5.3.3
  dropdown_button2: ^1.8.9
  file_picker: ^5.0.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.3
  flutter_easyloading: ^3.0.5
  flutter_file_downloader: ^1.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^15.1.1
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^1.1.6
  get: 4.6.5
  get_cli: ^1.8.1
  get_storage: ^2.0.3
  http: ^0.13.5
  image_picker: ^0.8.6
  in_app_review: ^2.0.8
  is_first_run: ^1.0.0
  lazy_load_scrollview: ^1.3.0
  local_auth: ^2.1.8
  network_info_plus: ^4.1.0
  path_provider: ^2.0.5
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  pusher_channels_flutter: ^2.2.0
  sentry_flutter: ^7.12.0
  shared_preferences: ^2.0.17
  showcaseview: ^2.0.3
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  test: ^1.22.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-lg.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - shorebird.yaml

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Black.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Arabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Arabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Arabic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Arabic-ExtraLight.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Arabic-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Arabic-Thin.ttf
          weight: 100
